name = "PlasmaFormulary"
uuid = "d26ff896-aba2-4e70-a0a6-448627456efe"
authors = ["Zijin Zhang", "Luke Adams <luke@lukeclydeadams.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulEquivalences = "da9c4bc3-91c8-4f02-8a40-6b990d2a7e0c"

[compat]
Aqua = "0.8"
Test = "1.10"
Unitful = "1.0"
UnitfulEquivalences = "0.2"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
